maxrequeuetime: 5             # 最大重入队列次数
clusters:                     # 集群列表
  - cluster:
      clusterName: 本地集群   # 自定义集群名
      insecure: false          # 是否开启跳过tls证书认证
      configPath: /root/.kube/config # kube config配置文件地址
      list:                   # 列表：目前支持：pods services configmaps secrets 等资源对象的监听
        - rType: pods         # 资源对象
          namespace: all      # namespace：可支持特定namespace或all
        - rType: deployments
          namespace: all
        - rType: events
          namespace: all
        - rType: secrets
          namespace: all
        - rType: statefulsets
          namespace: all
